#!/bin/sh
xset -dpms     # disable DPMS (Energy Star) features.
xset s off       # disable screen saver
xset s noblank # don't blank the video device
unclutter &
matchbox-window-manager &
sudo python /home/pi/Desktop/Django/PT/manage.py runserver
midori -e Fullscreen -a http://localhost:8000/paccotest/ouverture/
